annotations:
  category: Infrastructure
  licenses: |
    - Apache-2.0
apiVersion: v2
appVersion: 3.8.0
dependencies:
- name: common
  repository: "file://charts"
  tags:
  - bitnami-common
  version: 2.x.x
description: Apache ZooKeeper provides a reliable, centralized register of configuration
  data and services for distributed applications.
home: https://github.com/bitnami/charts/tree/main/bitnami/zookeeper
icon: https://bitnami.com/assets/stacks/zookeeper/img/zookeeper-stack-220x234.png
keywords:
- zookeeper
maintainers:
- name: Bitnami
  url: https://github.com/bitnami/charts
name: zookeeper
sources:
- https://github.com/bitnami/containers/tree/main/bitnami/zookeeper
- https://zookeeper.apache.org/
version: 11.1.0
