---
{{- if $.Values.global.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.global.rbac.roleName }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - "get"
      - "list"
      - "create"
      - "patch"
      - "update"
{{- end }}

---
{{- if $.Values.global.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.global.rbac.roleBindingName }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.global.rbac.roleName }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ .Values.global.rbac.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
{{- end }}
